<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.adplatform</groupId>
  <artifactId>ad-click-platform</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>

  <modules>
    <module>proto</module>
    <module>data-generator</module>
    <module>ingestion-service</module>
    <module>recommendation-service</module>
  </modules>

  <properties>
    <java.version>17</java.version>
    <grpc.version>1.62.2</grpc.version>
    <protobuf.version>3.25.1</protobuf.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-bom</artifactId>
        <version>${grpc.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.xolstice.maven.plugins</groupId>
          <artifactId>protobuf-maven-plugin</artifactId>
          <version>0.6.1</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
